DROP TABLE 	DOSSIERS;
DROP TABLE	CLIENTS;
DROP TABLE	VEHICULES;
DROP TABLE	AGENCES; 
DROP TABLE 	MODELES;
DROP TABLE 	MARQUES;
DROP TABLE 	CATEGORIES;
DROP TABLE 	TARIFS;
DROP TABLE	COULEURS;
DROP TABLE	PAYS;
DROP TABLE	VILLES;

